// Package pkg provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package pkg

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error       map[string]string `json:"error"`
	PhoneNumber string            `json:"phoneNumber"`
}

// PhoneNumberResponse defines model for PhoneNumberResponse.
type PhoneNumberResponse struct {
	AreaCode         string `json:"areaCode"`
	CountryCode      string `json:"countryCode"`
	LocalPhoneNumber string `json:"localPhoneNumber"`
	PhoneNumber      string `json:"phoneNumber"`
}

// GetV1PhoneNumbersParams defines parameters for GetV1PhoneNumbers.
type GetV1PhoneNumbersParams struct {
	PhoneNumber string  `form:"phoneNumber" json:"phoneNumber"`
	CountryCode *string `form:"countryCode,omitempty" json:"countryCode,omitempty"`
}
