// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	pkg "oxio-phone-lookup/internal/pkg"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// LookupPhoneNumber provides a mock function with given fields: params
func (_m *Service) LookupPhoneNumber(params pkg.GetV1PhoneNumbersParams) (*pkg.PhoneNumberResponse, error) {
	ret := _m.Called(params)

	if len(ret) == 0 {
		panic("no return value specified for LookupPhoneNumber")
	}

	var r0 *pkg.PhoneNumberResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(pkg.GetV1PhoneNumbersParams) (*pkg.PhoneNumberResponse, error)); ok {
		return rf(params)
	}
	if rf, ok := ret.Get(0).(func(pkg.GetV1PhoneNumbersParams) *pkg.PhoneNumberResponse); ok {
		r0 = rf(params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pkg.PhoneNumberResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(pkg.GetV1PhoneNumbersParams) error); ok {
		r1 = rf(params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
